Improve landing page copy
infinum/eightshift-docs pull request #142
Opened 2022-03-04 13:50 UTC by mbmjertan

# Description

After some discussion with @dingo-d, I've taken the liberty of rewriting the landing page copy a bit, as I noticed there was room to improve. 

Looking forward to feedback here!

2022-03-04 13:57 UTC, iobrado approved these changes
Nice!

2022-03-04 13:59 UTC, goranalkovic-infinum requested changes
Left a comment and a suggestion. Amazing work!

2022-03-04 13:59 UTC, goranalkovic-infinum commented on website/src/theme/sections/features/features.js
> +      desc: 'Declare breakpoints once, use them anywhere: from media queries to blocks. Override any attribute value for particular breakpoints without breaking a sweat. Need to tweak that width for
```suggestion
      desc: 'Declare breakpoints once, use them everywhere — from media queries to blocks. Override any attribute value for particular breakpoints without breaking a sweat. Need to tweak that width for tablets? Done.',
```

2022-03-04 13:59 UTC, goranalkovic-infinum commented on website/src/theme/sections/features/features.js
> +      desc: 'Eightshift Development kit comes with Webpack preconfigured. Build your JavaScript and CSS assets without breaking a sweat. Vendor prefixes? Polyfills? SCSS compilation? Asset minificati
```suggestion
      desc: 'Eightshift Development kit comes with Webpack preconfigured, so you can start building your JavaScript and CSS assets from the start. Vendor prefixes? Polyfills? SCSS compilation? Asset minification? All taken care of!'
```
Maybe too many _without breaking a sweat_-s in one part of the page 😄

2022-03-04 13:59 UTC, goranalkovic-infinum commented on website/src/theme/sections/get-started/get-started.js
> +          subtitle={'Boilerplate your project in a few simple steps. Get instructions for setting up an Eightshift Development kit theme or plugin, run a command (or two) and start coding. It\'s that
```suggestion
          subtitle={'Boilerplate your project in a few simple steps. Get instructions for setting up an Eightshift Development kit theme or plugin, run a command (or two) and start coding. It\'s that easy!'}
```

2022-03-06 10:52 UTC, dingo-d approved these changes
Nothing to add, apply the suggestions Goc added and it's good to go 🙂 

Great work 👍🏼

2022-03-07 08:10 UTC, goranalkovic-infinum approved these changes

2022-03-07 09:01 UTC, merged