adding chapters
infinum/eightshift-docs pull request #270
Opened 2023-09-18 13:19 UTC by iruzevic

# Description

- adding chapters

2023-09-18 13:28 UTC, piqusy requested changes
Looking good 👏🏼 

Just one wording suggestion

2023-09-18 13:28 UTC, piqusy commented on website/forms/features/geolocation.md
> +If you have Cloudflare turned on you your project please make sure that you read the [Cloudflare documentation](cloudflare) to make sure that the geolocation feature works as expected.
```suggestion
If you have Cloudflare turned on in your project please make sure that you read the [Cloudflare documentation](cloudflare) to make sure that the geolocation feature works as expected.
```

2023-09-18 13:35 UTC, iobrado requested changes
One minor change 🙂

2023-09-18 13:35 UTC, iobrado commented on website/forms/features/geolocation.md
> +* Europian Union
```suggestion
* European Union
```

2023-09-19 07:30 UTC, iobrado approved these changes

2023-09-19 07:41 UTC, piqusy approved these changes

2023-09-19 07:44 UTC, merged