Feature/forms
infinum/eightshift-docs pull request #271
Opened 2023-09-20 07:21 UTC by iruzevic

# Description

- adding new chapter

2023-09-20 08:28 UTC, piqusy requested changes
Looking good 👏🏼 

I have a few suggestions, feel free to disregard if you think the original wording is better.

2023-09-20 08:37 UTC, iobrado commented on website/forms/features/multisteps-forms.md
> +By utilizing the multi-step feature, you can craft a wide variety of custom forms. Each form can comprise numerous steps with fields, validation, and actions. Moreover, you can establish a flow betwe
I approve this suggestion 😄

2023-09-21 05:58 UTC, iobrado approved these changes

2023-09-21 06:40 UTC, piqusy approved these changes

2023-09-21 07:00 UTC, merged