updated checkAttrResponsive, updated checkAttr
infinum/eightshift-docs pull request #95
Opened 2021-05-19 12:18 UTC by volfkarlo

Changelog:
- updated chapter checkAttrResponsive
- updated checkAttr docs

2021-05-19 12:42 UTC, iruzevic submitted a review, later dismissed

2021-05-19 12:43 UTC, goranalkovic-infinum commented on website/docs/basics/helpers-php.md
> +This function is the really similar to the same JavaScript function on this [link](helpers-javascript). Except there is no last parameter which is used only in wp-admin to detect `undefined` attribut
```suggestion
This function is the PHP equivalent of [this JavaScript function](helpers-javascript), except there is no`undefinedAllowed` parameter, which is used only on the WordPress admin side.
```

2021-05-19 12:44 UTC, goranalkovic-infinum commented on website/docs/basics/helpers-php.md
> +This function is also the really similar to the same JavaScript function on this [link](helpers-javascript). Except there is no last parameter which is used only in wp-admin to detect `undefined` att
```suggestion
This function is the PHP equivalent of [this JavaScript function](helpers-javascript), except there is no `undefinedAllowed` parameter - it's used only on the WordPress admin side.
```

2021-05-19 13:26 UTC, dingo-d commented on website/docs/basics/helpers-javascript.md
> +Checks whether the attributes exist in the attributes list. If value is not set, it checks for default value. If default value is not set, it adds fallback value depending on type, or if `undefinedAl
```suggestion
Checks whether the attributes exist in the attributes list. If the value is not set, it checks for the default value. If the default value is not set, it adds a fallback value depending on the type, or if `undefinedAllowed` is set to `true`, it sets it to `undefined`.
```

2021-05-19 13:27 UTC, dingo-d requested changes
Small grammar fixes

2021-05-20 06:40 UTC, volfkarlo commented on website/docs/basics/helpers-php.md
> +This function is also the really similar to the same JavaScript function on this [link](helpers-javascript). Except there is no last parameter which is used only in wp-admin to detect `undefined` att
>Last isn't the best word here, as more parameters could be added in the future :)

I fully agree! 👍

2021-05-20 08:01 UTC, IvanGrginovInf approved these changes

2021-05-20 08:15 UTC, goranalkovic-infinum approved these changes

2021-05-20 09:14 UTC, dingo-d approved these changes

2021-05-20 12:03 UTC, merged