Update the webpack chapter with new entrypoint example.
infinum/eightshift-docs pull request #99
Opened 2021-06-01 15:57 UTC by gabriel-glo

This was needed for one of the recent projects and is a really useful thing.

2021-06-01 16:24 UTC, dingo-d submitted a review, later dismissed
Cool. What was the use case for this?

2021-06-01 18:08 UTC, iruzevic approved these changes

2021-06-02 07:14 UTC, IvanGrginovInf requested changes
Left a comment, otherwise looks great!

2021-06-02 07:14 UTC, IvanGrginovInf commented on website/docs/basics/webpack.md
> +Let's say you want to add a new, separate JS and/or CSS build for some specific functionality. This functionality may or may not have anything to do with your WordPress theme or plugin, but it needs
```suggestion
Let's say you want to add a new, separate JS and/or CSS build for some specific functionality. This functionality may or may not have anything to do with your WordPress theme or plugin, but it needs to be in separate files. To do that you'd need to add a new entrypoint for webpack to build in `webpack.config.js`:
```

2021-06-02 08:10 UTC, gabriel-glo commented
@dingo-d I needed this to style some embedded components (in iframes) that allowed linking to the external stylesheets. So I separated the styles for this embed with this method.

2021-06-02 08:59 UTC, IvanGrginovInf approved these changes

2021-06-02 10:10 UTC, merged